const pazartesi1 = {
  btn1: "#pageContent_rptList_rpChild_0_lbRezervasyon_0",
  btn2: "#pageContent_rptList_rpChild_0_lbRezervasyon_1",
  btn3: "#pageContent_rptList_rpChild_0_lbRezervasyon_2",
  btn4: "#pageContent_rptList_rpChild_0_lbRezervasyon_3",
  btn5: "#pageContent_rptList_rpChild_0_lbRezervasyon_4",
  btn6: "#pageContent_rptList_rpChild_0_lbRezervasyon_5",
  btn7: "#pageContent_rptList_rpChild_0_lbRezervasyon_6",
  btn8: "#pageContent_rptList_rpChild_0_lbRezervasyon_7",
  btn9: "#pageContent_rptList_rpChild_0_lbRezervasyon_8",
  btn10: "#pageContent_rptList_rpChild_0_lbRezervasyon_9",
  btn11: "#pageContent_rptList_rpChild_0_lbRezervasyon_10",
  btn12: "#pageContent_rptList_rpChild_0_lbRezervasyon_11",
  btn13: "#pageContent_rptList_rpChild_0_lbRezervasyon_12",
  btn14: "#pageContent_rptList_rpChild_0_lbRezervasyon_13",
  btn15: "#pageContent_rptList_rpChild_0_lbRezervasyon_14",
  btn16: "#pageContent_rptList_rpChild_0_lbRezervasyon_15",
};
const sali1 = {
  btn1: "#pageContent_rptList_rpChild_1_lbRezervasyon_0",
  btn2: "#pageContent_rptList_rpChild_1_lbRezervasyon_1",
  btn3: "#pageContent_rptList_rpChild_1_lbRezervasyon_2",
  btn4: "#pageContent_rptList_rpChild_1_lbRezervasyon_3",
  btn5: "#pageContent_rptList_rpChild_1_lbRezervasyon_4",
  btn6: "#pageContent_rptList_rpChild_1_lbRezervasyon_5",
  btn7: "#pageContent_rptList_rpChild_1_lbRezervasyon_6",
  btn8: "#pageContent_rptList_rpChild_1_lbRezervasyon_7",
  btn9: "#pageContent_rptList_rpChild_1_lbRezervasyon_8",
  btn10: "#pageContent_rptList_rpChild_1_lbRezervasyon_9",
  btn11: "#pageContent_rptList_rpChild_1_lbRezervasyon_10",
  btn12: "#pageContent_rptList_rpChild_1_lbRezervasyon_11",
  btn13: "#pageContent_rptList_rpChild_1_lbRezervasyon_12",
  btn14: "#pageContent_rptList_rpChild_1_lbRezervasyon_13",
  btn15: "#pageContent_rptList_rpChild_1_lbRezervasyon_14",
  btn16: "#pageContent_rptList_rpChild_1_lbRezervasyon_15",
};
const carsamba1 = {
  btn1: "#pageContent_rptList_rpChild_2_lbRezervasyon_0",
  btn2: "#pageContent_rptList_rpChild_2_lbRezervasyon_1",
  btn3: "#pageContent_rptList_rpChild_2_lbRezervasyon_2",
  btn4: "#pageContent_rptList_rpChild_2_lbRezervasyon_3",
  btn5: "#pageContent_rptList_rpChild_2_lbRezervasyon_4",
  btn6: "#pageContent_rptList_rpChild_2_lbRezervasyon_5",
  btn7: "#pageContent_rptList_rpChild_2_lbRezervasyon_6",
  btn8: "#pageContent_rptList_rpChild_2_lbRezervasyon_7",
  btn9: "#pageContent_rptList_rpChild_2_lbRezervasyon_8",
  btn10: "#pageContent_rptList_rpChild_2_lbRezervasyon_9",
  btn11: "#pageContent_rptList_rpChild_2_lbRezervasyon_10",
  btn12: "#pageContent_rptList_rpChild_2_lbRezervasyon_11",
  btn13: "#pageContent_rptList_rpChild_2_lbRezervasyon_12",
  btn14: "#pageContent_rptList_rpChild_2_lbRezervasyon_13",
  btn15: "#pageContent_rptList_rpChild_2_lbRezervasyon_14",
  btn16: "#pageContent_rptList_rpChild_2_lbRezervasyon_15",
};
const persembe1 = {
  btn1: "#pageContent_rptList_rpChild_3_lbRezervasyon_0",
  btn2: "#pageContent_rptList_rpChild_3_lbRezervasyon_1",
  btn3: "#pageContent_rptList_rpChild_3_lbRezervasyon_2",
  btn4: "#pageContent_rptList_rpChild_3_lbRezervasyon_3",
  btn5: "#pageContent_rptList_rpChild_3_lbRezervasyon_4",
  btn6: "#pageContent_rptList_rpChild_3_lbRezervasyon_5",
  btn7: "#pageContent_rptList_rpChild_3_lbRezervasyon_6",
  btn8: "#pageContent_rptList_rpChild_3_lbRezervasyon_7",
  btn9: "#pageContent_rptList_rpChild_3_lbRezervasyon_8",
  btn10: "#pageContent_rptList_rpChild_3_lbRezervasyon_9",
  btn11: "#pageContent_rptList_rpChild_3_lbRezervasyon_10",
  btn12: "#pageContent_rptList_rpChild_3_lbRezervasyon_11",
  btn13: "#pageContent_rptList_rpChild_3_lbRezervasyon_12",
  btn14: "#pageContent_rptList_rpChild_3_lbRezervasyon_13",
  btn15: "#pageContent_rptList_rpChild_3_lbRezervasyon_14",
  btn16: "#pageContent_rptList_rpChild_3_lbRezervasyon_15",
};
const cuma1 = {
  btn1: "#pageContent_rptList_rpChild_4_lbRezervasyon_0",
  btn2: "#pageContent_rptList_rpChild_4_lbRezervasyon_1",
  btn3: "#pageContent_rptList_rpChild_4_lbRezervasyon_2",
  btn4: "#pageContent_rptList_rpChild_4_lbRezervasyon_3",
  btn5: "#pageContent_rptList_rpChild_4_lbRezervasyon_4",
  btn6: "#pageContent_rptList_rpChild_4_lbRezervasyon_5",
  btn7: "#pageContent_rptList_rpChild_4_lbRezervasyon_6",
  btn8: "#pageContent_rptList_rpChild_4_lbRezervasyon_7",
  btn9: "#pageContent_rptList_rpChild_4_lbRezervasyon_8",
  btn10: "#pageContent_rptList_rpChild_4_lbRezervasyon_9",
  btn11: "#pageContent_rptList_rpChild_4_lbRezervasyon_10",
  btn12: "#pageContent_rptList_rpChild_4_lbRezervasyon_11",
  btn13: "#pageContent_rptList_rpChild_4_lbRezervasyon_12",
  btn14: "#pageContent_rptList_rpChild_4_lbRezervasyon_13",
  btn15: "#pageContent_rptList_rpChild_4_lbRezervasyon_14",
  btn16: "#pageContent_rptList_rpChild_4_lbRezervasyon_15",
};
const cumartesi1 = {
  btn1: "#pageContent_rptList_rpChild_5_lbRezervasyon_0",
  btn2: "#pageContent_rptList_rpChild_5_lbRezervasyon_1",
  btn3: "#pageContent_rptList_rpChild_5_lbRezervasyon_2",
  btn4: "#pageContent_rptList_rpChild_5_lbRezervasyon_3",
  btn5: "#pageContent_rptList_rpChild_5_lbRezervasyon_4",
  btn6: "#pageContent_rptList_rpChild_5_lbRezervasyon_5",
  btn7: "#pageContent_rptList_rpChild_5_lbRezervasyon_6",
  btn8: "#pageContent_rptList_rpChild_5_lbRezervasyon_7",
  btn9: "#pageContent_rptList_rpChild_5_lbRezervasyon_8",
  btn10: "#pageContent_rptList_rpChild_5_lbRezervasyon_9",
  btn11: "#pageContent_rptList_rpChild_5_lbRezervasyon_10",
  btn12: "#pageContent_rptList_rpChild_5_lbRezervasyon_11",
  btn13: "#pageContent_rptList_rpChild_5_lbRezervasyon_12",
  btn14: "#pageContent_rptList_rpChild_5_lbRezervasyon_13",
  btn15: "#pageContent_rptList_rpChild_5_lbRezervasyon_14",
  btn16: "#pageContent_rptList_rpChild_5_lbRezervasyon_15",
};
const pazar1 = {
  btn1: "#pageContent_rptList_rpChild_6_lbRezervasyon_0",
  btn2: "#pageContent_rptList_rpChild_6_lbRezervasyon_1",
  btn3: "#pageContent_rptList_rpChild_6_lbRezervasyon_2",
  btn4: "#pageContent_rptList_rpChild_6_lbRezervasyon_3",
  btn5: "#pageContent_rptList_rpChild_6_lbRezervasyon_4",
  btn6: "#pageContent_rptList_rpChild_6_lbRezervasyon_5",
  btn7: "#pageContent_rptList_rpChild_6_lbRezervasyon_6",
  btn8: "#pageContent_rptList_rpChild_6_lbRezervasyon_7",
  btn9: "#pageContent_rptList_rpChild_6_lbRezervasyon_8",
  btn10: "#pageContent_rptList_rpChild_6_lbRezervasyon_9",
  btn11: "#pageContent_rptList_rpChild_6_lbRezervasyon_10",
  btn12: "#pageContent_rptList_rpChild_6_lbRezervasyon_11",
  btn13: "#pageContent_rptList_rpChild_6_lbRezervasyon_12",
  btn14: "#pageContent_rptList_rpChild_6_lbRezervasyon_13",
  btn15: "#pageContent_rptList_rpChild_6_lbRezervasyon_14",
  btn16: "#pageContent_rptList_rpChild_6_lbRezervasyon_15",
};
const pazartesi2 = {
  btn1: "#pageContent_rptList_rpChild_7_lbRezervasyon_0",
  btn2: "#pageContent_rptList_rpChild_7_lbRezervasyon_1",
  btn3: "#pageContent_rptList_rpChild_7_lbRezervasyon_2",
  btn4: "#pageContent_rptList_rpChild_7_lbRezervasyon_3",
  btn5: "#pageContent_rptList_rpChild_7_lbRezervasyon_4",
  btn6: "#pageContent_rptList_rpChild_7_lbRezervasyon_5",
  btn7: "#pageContent_rptList_rpChild_7_lbRezervasyon_6",
  btn8: "#pageContent_rptList_rpChild_7_lbRezervasyon_7",
  btn9: "#pageContent_rptList_rpChild_7_lbRezervasyon_8",
  btn10: "#pageContent_rptList_rpChild_7_lbRezervasyon_9",
  btn11: "#pageContent_rptList_rpChild_7_lbRezervasyon_10",
  btn12: "#pageContent_rptList_rpChild_7_lbRezervasyon_11",
  btn13: "#pageContent_rptList_rpChild_7_lbRezervasyon_12",
  btn14: "#pageContent_rptList_rpChild_7_lbRezervasyon_13",
  btn15: "#pageContent_rptList_rpChild_7_lbRezervasyon_14",
  btn16: "#pageContent_rptList_rpChild_7_lbRezervasyon_15",
};
const sali2 = {
  btn1: "#pageContent_rptList_rpChild_8_lbRezervasyon_0",
  btn2: "#pageContent_rptList_rpChild_8_lbRezervasyon_1",
  btn3: "#pageContent_rptList_rpChild_8_lbRezervasyon_2",
  btn4: "#pageContent_rptList_rpChild_8_lbRezervasyon_3",
  btn5: "#pageContent_rptList_rpChild_8_lbRezervasyon_4",
  btn6: "#pageContent_rptList_rpChild_8_lbRezervasyon_5",
  btn7: "#pageContent_rptList_rpChild_8_lbRezervasyon_6",
  btn8: "#pageContent_rptList_rpChild_8_lbRezervasyon_7",
  btn9: "#pageContent_rptList_rpChild_8_lbRezervasyon_8",
  btn10: "#pageContent_rptList_rpChild_8_lbRezervasyon_9",
  btn11: "#pageContent_rptList_rpChild_8_lbRezervasyon_10",
  btn12: "#pageContent_rptList_rpChild_8_lbRezervasyon_11",
  btn13: "#pageContent_rptList_rpChild_8_lbRezervasyon_12",
  btn14: "#pageContent_rptList_rpChild_8_lbRezervasyon_13",
  btn15: "#pageContent_rptList_rpChild_8_lbRezervasyon_14",
  btn16: "#pageContent_rptList_rpChild_8_lbRezervasyon_15",
};
const carsamba2 = {
  btn1: "#pageContent_rptList_rpChild_9_lbRezervasyon_0",
  btn2: "#pageContent_rptList_rpChild_9_lbRezervasyon_1",
  btn3: "#pageContent_rptList_rpChild_9_lbRezervasyon_2",
  btn4: "#pageContent_rptList_rpChild_9_lbRezervasyon_3",
  btn5: "#pageContent_rptList_rpChild_9_lbRezervasyon_4",
  btn6: "#pageContent_rptList_rpChild_9_lbRezervasyon_5",
  btn7: "#pageContent_rptList_rpChild_9_lbRezervasyon_6",
  btn8: "#pageContent_rptList_rpChild_9_lbRezervasyon_7",
  btn9: "#pageContent_rptList_rpChild_9_lbRezervasyon_8",
  btn10: "#pageContent_rptList_rpChild_9_lbRezervasyon_9",
  btn11: "#pageContent_rptList_rpChild_9_lbRezervasyon_10",
  btn12: "#pageContent_rptList_rpChild_9_lbRezervasyon_11",
  btn13: "#pageContent_rptList_rpChild_9_lbRezervasyon_12",
  btn14: "#pageContent_rptList_rpChild_9_lbRezervasyon_13",
  btn15: "#pageContent_rptList_rpChild_9_lbRezervasyon_14",
  btn16: "#pageContent_rptList_rpChild_9_lbRezervasyon_15",
};
const persembe2 = {
  btn1: "#pageContent_rptList_rpChild_10_lbRezervasyon_0",
  btn2: "#pageContent_rptList_rpChild_10_lbRezervasyon_1",
  btn3: "#pageContent_rptList_rpChild_10_lbRezervasyon_2",
  btn4: "#pageContent_rptList_rpChild_10_lbRezervasyon_3",
  btn5: "#pageContent_rptList_rpChild_10_lbRezervasyon_4",
  btn6: "#pageContent_rptList_rpChild_10_lbRezervasyon_5",
  btn7: "#pageContent_rptList_rpChild_10_lbRezervasyon_6",
  btn8: "#pageContent_rptList_rpChild_10_lbRezervasyon_7",
  btn9: "#pageContent_rptList_rpChild_10_lbRezervasyon_8",
  btn10: "#pageContent_rptList_rpChild_10_lbRezervasyon_9",
  btn11: "#pageContent_rptList_rpChild_10_lbRezervasyon_10",
  btn12: "#pageContent_rptList_rpChild_10_lbRezervasyon_11",
  btn13: "#pageContent_rptList_rpChild_10_lbRezervasyon_12",
  btn14: "#pageContent_rptList_rpChild_10_lbRezervasyon_13",
  btn15: "#pageContent_rptList_rpChild_10_lbRezervasyon_14",
  btn16: "#pageContent_rptList_rpChild_10_lbRezervasyon_15",
};
const cuma2 = {
  btn1: "#pageContent_rptList_rpChild_11_lbRezervasyon_0",
  btn2: "#pageContent_rptList_rpChild_11_lbRezervasyon_1",
  btn3: "#pageContent_rptList_rpChild_11_lbRezervasyon_2",
  btn4: "#pageContent_rptList_rpChild_11_lbRezervasyon_3",
  btn5: "#pageContent_rptList_rpChild_11_lbRezervasyon_4",
  btn6: "#pageContent_rptList_rpChild_11_lbRezervasyon_5",
  btn7: "#pageContent_rptList_rpChild_11_lbRezervasyon_6",
  btn8: "#pageContent_rptList_rpChild_11_lbRezervasyon_7",
  btn9: "#pageContent_rptList_rpChild_11_lbRezervasyon_8",
  btn10: "#pageContent_rptList_rpChild_11_lbRezervasyon_9",
  btn11: "#pageContent_rptList_rpChild_11_lbRezervasyon_10",
  btn12: "#pageContent_rptList_rpChild_11_lbRezervasyon_11",
  btn13: "#pageContent_rptList_rpChild_11_lbRezervasyon_12",
  btn14: "#pageContent_rptList_rpChild_11_lbRezervasyon_13",
  btn15: "#pageContent_rptList_rpChild_11_lbRezervasyon_14",
  btn16: "#pageContent_rptList_rpChild_11_lbRezervasyon_15",
};
const cumartesi2 = {
  btn1: "#pageContent_rptList_rpChild_12_lbRezervasyon_0",
  btn2: "#pageContent_rptList_rpChild_12_lbRezervasyon_1",
  btn3: "#pageContent_rptList_rpChild_12_lbRezervasyon_2",
  btn4: "#pageContent_rptList_rpChild_12_lbRezervasyon_3",
  btn5: "#pageContent_rptList_rpChild_12_lbRezervasyon_4",
  btn6: "#pageContent_rptList_rpChild_12_lbRezervasyon_5",
  btn7: "#pageContent_rptList_rpChild_12_lbRezervasyon_6",
  btn8: "#pageContent_rptList_rpChild_12_lbRezervasyon_7",
  btn9: "#pageContent_rptList_rpChild_12_lbRezervasyon_8",
  btn10: "#pageContent_rptList_rpChild_12_lbRezervasyon_9",
  btn11: "#pageContent_rptList_rpChild_12_lbRezervasyon_10",
  btn12: "#pageContent_rptList_rpChild_12_lbRezervasyon_11",
  btn13: "#pageContent_rptList_rpChild_12_lbRezervasyon_12",
  btn14: "#pageContent_rptList_rpChild_12_lbRezervasyon_13",
  btn15: "#pageContent_rptList_rpChild_12_lbRezervasyon_14",
  btn16: "#pageContent_rptList_rpChild_12_lbRezervasyon_15",
};
const pazar2 = {
  btn1: "#pageContent_rptList_rpChild_13_lbRezervasyon_0",
  btn2: "#pageContent_rptList_rpChild_13_lbRezervasyon_1",
  btn3: "#pageContent_rptList_rpChild_13_lbRezervasyon_2",
  btn4: "#pageContent_rptList_rpChild_13_lbRezervasyon_3",
  btn5: "#pageContent_rptList_rpChild_13_lbRezervasyon_4",
  btn6: "#pageContent_rptList_rpChild_13_lbRezervasyon_5",
  btn7: "#pageContent_rptList_rpChild_13_lbRezervasyon_6",
  btn8: "#pageContent_rptList_rpChild_13_lbRezervasyon_7",
  btn9: "#pageContent_rptList_rpChild_13_lbRezervasyon_8",
  btn10: "#pageContent_rptList_rpChild_13_lbRezervasyon_9",
  btn11: "#pageContent_rptList_rpChild_13_lbRezervasyon_10",
  btn12: "#pageContent_rptList_rpChild_13_lbRezervasyon_11",
  btn13: "#pageContent_rptList_rpChild_13_lbRezervasyon_12",
  btn14: "#pageContent_rptList_rpChild_13_lbRezervasyon_13",
  btn15: "#pageContent_rptList_rpChild_13_lbRezervasyon_14",
  btn16: "#pageContent_rptList_rpChild_13_lbRezervasyon_15",
};

const CORTS = {
  KAPALI_1: "Kapalı Tenis Kortu 1",
  KAPALI_2: "Kapalı Tenis Kortu 2",
  KAPALI_3: "Kapalı Tenis Kortu 3",
  KAPALI_4: "Kapalı Tenis Kortu 4",
  KAPALI_5: "Kapalı Tenis Kortu 5",
  KAPALI_6: "Kapalı Tenis Kortu 6",
  ACIK_2: "Açık Tenis Kortu 2",
  TOPRAK_1: "Açık Toprak Tenis Kortu 1",
  TOPRAK_2: "Açık Toprak Tenis Kortu 2",
  TOPRAK_3: "Açık Toprak Tenis Kortu 3",
};

module.exports = {
  pazartesi1,
  pazartesi2,
  sali1,
  sali2,
  carsamba1,
  carsamba2,
  persembe1,
  persembe2,
  cuma1,
  cuma2,
  cumartesi1,
  cumartesi2,
  pazar1,
  pazar2,
  CORTS,
};
